### ISSUE TITLE
mod dead?

### ISSUE THREAD

**Issue by Prophious** [iconmaster5326/AetherCraft#39]
is this mod dead, as it seems that there is no actions for about 10+ months from dev

**Comment by iconmaster5326** [comment]
Yes, AetherCraft is no longer in active production. I might, however, accept pull requests.

Currently, I'm working on a new version of AetherCraft at [https://www.github.com/iconmaster5326/AetherCraft2](https://www.github.com/iconmaster5326/AetherCraft2) .
